### PR TITLE
Added O3DCon Banner to the website

### PR DESCRIPTION
**Pull request by aFinchy**
## Change summary

Added O3DCon Banner to the Website, 
Shows on the following pages:
- Home
- Downloads
- Contribute
- Community

Screenshot 2022-06-28 at 21-20-38 O3DE

### CODE REVIEW

**Comment by aFinchy** [comment]
This was Requested by Nicole at the Linux Foundation

**Comment by aFinchy** [comment]
**Updated the color to purple**

unknown

**Hover-over color a slightly darker purple**

Capture121

**Comment by aFinchy** [comment]
Updated the Text of REGISTER to Purple
Capture121

**Review by AMZN-daimini — APPROVED** [review]
A couple suggestions below, but looks good! :)

**Review by FiniteStateGit — APPROVED** [review]
Checked on mobile, lgtm!

**Pull request merged**
