### PR TITLE
Add Tencent and Gamepoch to partners list

### PR DESCRIPTION
**Pull request by AMZN-daimini**
image
image

Ensured the logos are displayed correctly in mobile resolutions too.

Signed-off-by: Danilo Aimini <82231674+AMZN-daimini@users.noreply.github.com>

### CODE REVIEW

**Review by sptramer — APPROVED** [review]
LGTM - only concern would be the Gamepoch logo not being an SVG, but I was unable to find a vector graphics resource for it.

**Comment by sptramer** [comment]
Requested second reviewer is @uoduckswtd1 (not currently in the docs reviewers pool) who is the LF Marketing lead for O3DE.

**Comment by AMZN-daimini** [comment]
> LGTM - only concern would be the Gamepoch logo not being an SVG, but I was unable to find a vector graphics resource for it.

I second this, but I could not find an svg myself :(

**Review by micronAMZN — APPROVED** [review]

**Comment by AMZN-daimini** [comment]
@sptramer do we need to wait for a confirmation, or can this be merged?

**Comment by sptramer** [comment]
Waiting on confirmation from the LF via https://github.com/uoduckswtd1 - there is a question about which Tencent logo should appear.

**Comment by theheels** [comment]
@AMZN-daimini Doing some cleanup and realized this is not yet resolved. The logos in are mockup is correct, can you merge this?

**Pull request merged**
