### PR TITLE
Linux simplification

### PR DESCRIPTION
**Pull request by amznestebanpapp**
## Change summary

Removes parameters that are no longer required (Linux compiler detection now picks up clang). 

### Submission Checklist:

* [NA] **Descriptive active voice** - Do descriptive sentences have a clear *subject* and *action verb*?
* [NA] **Answer the question at hand** - Does the documentation answer a *what*, *why*, *how*, or *where* type of question?
* [NA] **Consistency** - Does the content consistently follow the [style guide](https://o3de.org/docs/contributing/to-docs/style-guide/)?
* [NA] **Help the user** - Does the documentation show the user something *meaningful*?

### CODE REVIEW

**Review by willihay — APPROVED** [review]

**Comment by willihay** [comment]
Since this PR is not about the website or the installer documentation, it can be merged to main instead of stabilization, unless there's a good reason to hold it until December.

**Comment by amznestebanpapp** [comment]
> Since this PR is not about the website or the installer documentation, it can be based to main instead of stabilization, unless there's a good reason to hold it until December.

No reason, re-targetting

**Comment by willihay** [comment]
> > Since this PR is not about the website or the installer documentation, it can be based to main instead of stabilization, unless there's a good reason to hold it until December.
> 
> Seems that it was already fixed in [`c65afbf5eb0e4d8b8cd09326c9654ac2d8929997`](https://github.com/o3de/o3de.org/commit/c65afbf5eb0e4d8b8cd09326c9654ac2d8929997#diff-220ea4795326b3fa9b894917207eb5d9da4ae942ec8858524b8ddeec8f09b7b3) will that branch eventually be merged to this one? if it will, I can drop this. If not, this can be fixed in this branch.

Oh! Thought it looked familiar. Had forgotten what spham had changed there. In that case, this PR can be closed. The change has already been made and is live on the website. The staging/2111 is just a bit behind.

**Comment by amznestebanpapp** [comment]
Closing, thanks

**Pull request closed without merging**
