### PR TITLE
Website - Limit anchor scrolling to table of contents

### PR DESCRIPTION
**Pull request by AMZN-daimini**
Fix to limit the newly added anchor scroll behavior to the table of contents.

### CODE REVIEW

**Comment by FiniteStateGit** [comment]
Posted in discord but take a look at H3 anchor links: https://deploy-preview-1184--o3deorg.netlify.app/docs/user-guide/components/reference/atom/light/#shadows-properties

**Comment by AMZN-daimini** [comment]
> Posted in discord but take a look at H3 anchor links: https://deploy-preview-1184--o3deorg.netlify.app/docs/user-guide/components/reference/atom/light/#shadows-properties

Good spot, I changed it again to explicitly skip tabs, but keep the behavior for other anchors.

**Review by FiniteStateGit — APPROVED** [review]
Looks good. Approved.

**Comment by FiniteStateGit** [comment]
Fix #1235

**Review by willihay — APPROVED** [review]

**Pull request merged**
