### PR TITLE
Edit headings user-guide/project-config/cli-reference

### PR DESCRIPTION
**Pull request by FiniteStateGit**
The page table of contents was long and repetitive; I changed headings so repeating subsections did not appear in the page's TOC.

### CODE REVIEW

**Review by sptramer — CHANGES_REQUESTED** [review]
Rejected. These changes don't materially improve the page, and damage the ability to navigate by right-hand ToC.

**Comment by sptramer** [comment]
Going to reopen for the 2nd opinion. We require 2 reviews to merge, so should require two to reject.

**Comment by FiniteStateGit** [comment]
I found this change questionable as well.  I'd be willing to close this PR.

**Comment by chanmosq** [comment]
I agree that this change isn't necessary, makes navigation more difficult (some subsections are incredibly long), and causes other styling problems. Changing them to Header 4's removes the header's _text_ in the right-hand TOC, however it leaves a space there (see image). That's a website issue, though. 

Since @sptramer also rejected it, I'll go ahead and close this PR. 
image

**Pull request closed without merging**
