### PR TITLE
SPEC-7660 | Improve Learn Page's Navigation

### PR DESCRIPTION
**Pull request by AMZN-daimini**
WIP for the O3DE LEARN menu changes. Mostly creating this PR so we can discuss the progress with a live version of the website changes at hand.

### CODE REVIEW

**Review by erickson-doug — APPROVED** [review]

**Comment by erickson-doug** [comment]
@AMZN-daimini Is this ready for merge? Looks GREAT across my three test devices -- glorious work on the ToC. When yer ready, please move it out of draft for merge and lemme know.

**Comment by AMZN-daimini** [comment]
Still have some minor fixes to apply, but wanted to have a live version of the page to use to discuss them :) Should be ready soon though!

**Comment by AMZN-daimini** [comment]
Added some other functionalities (most notably the mobile docs menu) and fixed some minor issues and visual details. Ready for review :)

**Review by amzn-leenguy — APPROVED** [review]
SHIP IT

**Comment by erickson-doug** [comment]
@AMZN-daimini We have a merge conflict -- can you resolve?

**Comment by AMZN-daimini** [comment]
I resolved the merge conflict, but I would request a new review to make sure I did not break anything in the process :)

**Comment by chanmosq** [comment]
Awesome!

**Pull request merged**
