### PR TITLE
Main to dev/220816

### PR DESCRIPTION
**Pull request by sptramer**
## Change summary

Merge from `main` to `development`, resolving any conflicts. It turns out that these merges are complicated whenever there is a change in whitespacing, UTF-8 characters like smart quotes, CLRF translations, and other minor text changes that introduce conflicts which git should, in theory, be able to resolve entirely reasonably on its own. Regrettably `patch` was not made with English language text in mind.

The following is a list of files with conflicts which were edited. Before merge reviewers should do a quick check and ensure that the correct changes were accepted.

```
content/docs/atom-guide/dev-guide/materials/lua-material-functor-api.md
content/docs/atom-guide/look-dev/materials/material-file-spec.md
content/docs/atom-guide/look-dev/materials/material-system.md
content/docs/atom-guide/look-dev/materials/material-type-file-spec.md
content/docs/contributing/to-docs/overview.md
content/docs/user-guide/assets/asset-processor/_index.md
content/docs/user-guide/assets/asset-processor/faster-scanning.md
content/docs/user-guide/gems/reference/multiplayer/_index.md
content/docs/user-guide/interactivity/audio/advanced-topics/audio-panning-mode.md
content/docs/user-guide/interactivity/navigation-and-pathfinding/_index.md
content/docs/user-guide/interactivity/physics/nvidia-physx/configuring/configuration-global.md
content/docs/user-guide/scripting/lua/debugging-tutorial.md
content/docs/user-guide/scripting/script-canvas/programmer-guide/_index.md
content/docs/user-guide/scripting/script-canvas/programmer-guide/custom-nodes/_index.md
content/docs/welcome-guide/key-concepts.md
```

`git diff --check` returned clean for conflict markers on the `main-to-dev` branch.

### Submission Checklist:

* [ ] **Descriptive active voice** - Do descriptive sentences have a clear *subject* and *action verb*?
* [ ] **Answer the question at hand** - Does the documentation answer a *what*, *why*, *how*, or *where* type of question?
* [x] **Consistency** - Does the content consistently follow the [style guide](https://o3de.org/docs/contributing/to-docs/style-guide/)?
* [ ] **Help the user** - Does the documentation show the user something *meaningful*?

### CODE REVIEW

**Comment by sptramer** [comment]
Looks like there is a DCO issue with some contributions from Lionbridge and a handful of others. Will add a secondary sign-off to any of these commits later. Shouldn't block review of the merge.

**Comment by FiniteStateGit** [comment]
I checked everything below `content/docs/user-guide/gems/reference/multiplayer/_index.md` on the list and everything appears to have the most up-to-date information.  I did not see any diff to check for `content/docs/user-guide/interactivity/audio/advanced-topics/audio-panning-mode.md` but the page does exist in the preview (it wasn't deleted).

**Review by FiniteStateGit — APPROVED** [review]

**Review by willihay — APPROVED** [review]
I checked the merge conflict resolution for the contributing and welcome guide pages as well as the assets, multiplayer, and scripting pages in the user guide. I think the only section remaining to check are the atom guide pages.

**Review by micronAMZN — APPROVED** [review]

**Comment by chanmosq** [comment]
Atom Guide docs look good!

**Review by chanmosq — APPROVED** [review]

**Comment by willihay** [comment]
I don't understand this DCO error. My correct signature is there.

**Comment by micronAMZN** [comment]
> I don't understand this DCO error. My correct signature is there in the commit. Needs further investigation.

Tried to amend the signoff and it didn't work.

**Comment by sptramer** [comment]
I know what it is - I didn't sign my merge commits! I'll see if I can find them in the history, fix the DCO, and resubmit. It looks like there have been some new conflicts introduced in the last week as well.

**Pull request merged**
