### PR TITLE
Backport #2551

### PR DESCRIPTION
**Pull request by nbbrooks**
## Change summary
This updates 2310.1 documentation to add the missing WarehouseAutomation gem that attempting to build the Manipulation demo will complain about.

I do not know if #2551 can be directly backported to the 2310.1 docs, so here I am just adding it maually.

### Submission Checklist:

* [ ] **Descriptive active voice** - Do descriptive sentences have a clear *subject* and *action verb*?
* [ ] **Answer the question at hand** - Does the documentation answer a *what*, *why*, *how*, or *where* type of question?
* [ ] **Consistency** - Does the content consistently follow the [Style Guide](https://o3de.org/docs/contributing/to-docs/style-guide/quick-reference)?
* [ ] **Help the user** - Does the documentation show the user something *meaningful*?

### CODE REVIEW

**Review by adamdbrw — APPROVED** [review]

**Comment by ShaunaGordon** [comment]
@nbbrooks We're working on cleaning up PRs and tightening our process on this repo to bring it in line with the main O3DE repo. Is this change already in the development branch? If not, can you please update this PR to merge into development instead? We can then cherry-pick into main if necessary.

**Comment by nbbrooks** [comment]
I have not looked at this repo in a while, but the intent on this was to fix documentation which resulted in a build error due to an needed asset not being registered. 

#2551 already fixed the documentation on [development](https://github.com/o3de/o3de.org/blob/development/content/docs/user-guide/interactivity/robotics/project-configuration.md) using `register --all-gems-path` instead of individual gem registration, but I was unclear on if that feature was available in 2310.

So in summary
- development docs does NOT have an issue with the WarehouseAutomation gem not being registered
-  [main](https://github.com/o3de/o3de.org/blob/main/content/docs/user-guide/interactivity/robotics/project-configuration.md) does
- [version/2310](https://github.com/o3de/o3de.org/blob/version/2310/content/docs/user-guide/interactivity/robotics/project-configuration.md) does

I am not sure why this PR is targeting main though - was the 2310 branch renamed to "version/2310" ? Maybe GH retargeted this to main for some reason.

**Comment by ShaunaGordon** [comment]
Awesome, thanks for the info! I'll see about getting some verification and probably merge it as-is, unless someone recommends otherwise.

**Review by spham-amzn — APPROVED** [review]

**Comment by ShaunaGordon** [comment]
@RoddieKieley Good to merge this one **into branch version/2310** (it's currently set to merge into main, that is incorrect).

**Comment by adamdbrw** [comment]
@nbbrooks could you switch the PR target to 2310?

**Comment by nbbrooks** [comment]
retargeted!

**Pull request merged**
