### PR TITLE
Increased the number list in the tool UI

### LINKED ISSUE #836: [ISSUE][DOCS] Numbers in the ordered lists in Tools UI Component Library don't increment
## Describe the issue

The numbers in the ordered lists in various pages of the Tools UI Component Library do not increment. They remain at "1."

## Impacted page(s)

Examples include:

https://o3de.org/docs/tools-ui/component-library/uidev-browse-edit-component/#anatomy-of-the-browse-edit-widgeta-namebrowse-edit-anatomya

https://o3de.org/docs/tools-ui/component-library/uidev-button-component/#usage-guidelinesa-namebutton-usagea

(Also, the section links are a weird combination of formatting.)

## Expected experience

Ordered lists that increment properly.

### PR DESCRIPTION
**Pull request by Shyamalsian**
Fixes #836

### CODE REVIEW

**Comment by sptramer** [comment]
Hi @Shyamalsian, before we can merge your pull request we require that you sign off with the [Developer Certificate of Origin](https://developercertificate.org/), our form of attribution to an individual for any given commit. To fix the DCO on this pull request, please follow the [Fix single-commit DCO instructions](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md#fix-option-1-amend-single-commit).

**Review by sptramer — APPROVED** [review]
Approved pending DCO fix.

**Comment by Shyamalsian** [comment]
I can't understand can u please explain it to me.

**Comment by willihay** [comment]
All commits need to be signed with a specific format in the commit message. For this pull request, you should be able to fix your commit using the instructions provided in the DCO "Details" link at the bottom of the PR: [https://github.com/o3de/o3de.org/pull/857/checks?check_run_id=3474732238](https://github.com/o3de/o3de.org/pull/857/checks?check_run_id=3474732238)

**Comment by Shyamalsian** [comment]
Changes have been made  PR no. #864

**Comment by sptramer** [comment]
Closing in favor of #864 as per author.

**Pull request closed without merging**
