### PR TITLE
Add new favicon, logos and media assets for the release of for 22.05.0

### PR DESCRIPTION
**Pull request by mxrmrtz**
## Change summary

* Updates all favicons, logos and also update logos within images mentioned here: https://github.com/o3de/o3de/issues/9253#issuecomment-1118850307

* Updates version references in `layouts/partials/download/content-linux.html` and `layouts/partials/download/content-windows.html` that was missed in the other PR containing the release notes for 22.05.0.

**Notice**: There where a list of assets we could not update due to the nature of the asset. This has been okay'd by @theheels. Here is the list of said assets for reference;

**Images containing logo as 3d object**

```
static\images\learning-guide\tutorials\assets\convex-collider-example.png
 static\images\learning-guide\tutorials\assets\convex-decompose.png
 static\images\learning-guide\tutorials\assets\meshes-finished.png
 static\images\learning-guide\tutorials\assets\meshes-search-asset-browser.png
 static\images\learning-guide\tutorials\assets\physx-entity.png
 static\images\learning-guide\tutorials\assets\primitive-collider-example.png
 static\images\learning-guide\tutorials\assets\primitive-decompose.png
 static\images\learning-guide\tutorials\assets\triangle-mesh-collider-example.png
```
**Youtube thumbnails**
We changed the video thumbnails on the website, but thumbnails on the youtube channel needs to be changed.

Stakeholder: @theheels

### Submission Checklist:

* [x] **Descriptive active voice** - Do descriptive sentences have a clear *subject* and *action verb*?
* [x] **Answer the question at hand** - Does the documentation answer a *what*, *why*, *how*, or *where* type of question?
* [x] **Consistency** - Does the content consistently follow the [style guide](https://o3de.org/docs/contributing/to-docs/style-guide/)?
* [x] **Help the user** - Does the documentation show the user something *meaningful*?

### CODE REVIEW

**Review by micronAMZN — APPROVED** [review]
Awesome, thanks for this! One comment, this image `static/images/welcome-guide/wg-welcome-page-color.png` is removed in #1620 which will be merged for release. You can remove it from this PR. It's only used in a style guide example, so I replaced with with an existing guide image that has no logo.

**Comment by mxrmrtz** [comment]
> Awesome, thanks for this! One comment, this image `static/images/welcome-guide/wg-welcome-page-color.png` is removed in #1620 which will be merged for release. You can remove it from this PR. It's only used in a style guide example, so I replaced with with an existing guide image that has no logo.
> 
> The other assets you are referring to will all be covered in #1620.

Thanks for noticing!  It has now been removed.

**Comment by micronAMZN** [comment]
Actually, scratch that, the tutorial images mentioned in the commit will be in a new PR.

**Comment by micronAMZN** [comment]
Hold label added, will merge on release call.

**Comment by mxrmrtz** [comment]
> Actually, scratch that, the tutorial images mentioned in the commit will be in a new PR.

Okay noted! Reverted the change :)

**Comment by amzn-leenguy** [comment]
In reviewing this, it seems we have covered all the instances of the logo from a global website point of view, but there still instances that we may need to update on the blog article images themselves. (Thanks for updating the thumbnails too)

@mxrmrtz Are you want to update those as well? 

Also just a question: 

Was there a reason why we chose to use the mono version of the new O3DE logo over the the colored one?

Thanks

**Review by FiniteStateGit — APPROVED** [review]
I don't consider this blocking, but the branding guidelines .pdf should be updated.

https://www.o3de.org/files/Open-3D-Branding-Guidelines-June-2021.pdf

If someone has the opportunity to call it out as a post-release task, please do.

**Comment by amzn-leenguy** [comment]
> I don't consider this blocking, but the branding guidelines .pdf should be updated.
> 
> https://www.o3de.org/files/Open-3D-Branding-Guidelines-June-2021.pdf
> 
> If someone has the opportunity to call it out as a post-release task, please do.

This is a good call out. Linux Foundation are aware that the Style Guide is out of date, and I have notified them that this asset needs to be updated to complete the rebrand. But we may need to create a separate task for this, as we do not have an ETA on when the new style guide will be complete.

**Comment by yuyihsu** [comment]
> > I don't consider this blocking, but the branding guidelines .pdf should be updated.
> > https://www.o3de.org/files/Open-3D-Branding-Guidelines-June-2021.pdf
> > If someone has the opportunity to call it out as a post-release task, please do.
> 
> This is a good call out. Linux Foundation are aware that the Style Guide is out of date, and I have notified them that this asset needs to be updated to complete the rebrand. But we may need to create a separate task for this, as we do not have an ETA on when the new style guide will be complete.

In addition to the style guide, the logo pack is the old one too.

**Comment by mxrmrtz** [comment]
> In reviewing this, it seems we have covered all the instances of the logo from a global website point of view, but there still instances that we may need to update on the blog article images themselves. (Thanks for updating the thumbnails too)
> 
> @mxrmrtz Are you want to update those as well?
> 
> Also just a question:
> 
> Was there a reason why we chose to use the mono version of the new O3DE logo over the the colored one?
> 
> Thanks

Hi all, we can definitely change the header / footer logo to the colored version but wanted to keep visual changes to a minimum for this PR to not introduce regression bugs. 
 
It is a tad unclear to me if I have the ability to make these calls so I’ll refer to @theheels for this discussion.

Regarding the blog article, are we talking about /blog/posts/intro-to-bjds/? If so i can make these changes.

**Comment by amzn-leenguy** [comment]
> > > I don't consider this blocking, but the branding guidelines .pdf should be updated.
> > > https://www.o3de.org/files/Open-3D-Branding-Guidelines-June-2021.pdf
> > > If someone has the opportunity to call it out as a post-release task, please do.
> > 
> > 
> > This is a good call out. Linux Foundation are aware that the Style Guide is out of date, and I have notified them that this asset needs to be updated to complete the rebrand. But we may need to create a separate task for this, as we do not have an ETA on when the new style guide will be complete.
> 
> In addition to the style guide, the logo pack is the old one too.

Here is the consolidated list I recommend we address to complete the rebrand:

- A style guide detailing the different formats and and icons, with mock up examples.
- A logo pack with Folder structure. This will also have all the different formats and sizes. (You can [download my ZIP file](https://www.o3de.org/files/O3DE-Logo-Pack.zip) for a folder reference of files expected for a industry standard logo pack – Also make sure to include Regular, Reverse, Mono, Mono Reverse and, PNG, SVG, JPG and EPS)
- Branding collaterals or mock up examples. [This PR](https://github.com/o3de/o3de/pull/9282) has some good screenshots that can provide context for UI examples.
- Assets Update to the [O3DE Website](https://o3de.org/). Logo’s need to be replaced in any reference on all pages. (This is that PR)
- Updates to the [Branding website](https://www.o3de.org/docs/tools-ui/branding-guidelines/) for O3DE logo. (This is that PR)
- Update to the O3DE Docs Footer logo. (This is that PR)
- A press kit that people can download for announcements for the new O3DE release.

**Comment by amzn-leenguy** [comment]
> Hi all, we can definitely change the header / footer logo to the colored version but wanted to keep visual changes to a minimum for this PR to not introduce regression bugs.

I appreciate you making these changes. If I was making the creative direction, I would use the coloured version in the header, but have the mono reversed version you have today in the footer. Since this is normally the most common pattern on websites.

> It is a tad unclear to me if I have the ability to make these calls so I’ll refer to @theheels for this discussion.

Ok. Good to know. This may be a branding call from Linux Foundation if they consider the Coloured version or the Mono version as their primary logo for O3DE. _Normally_ a coloured version of a logo is considered the default / regular one, and the mono version is considered the secondary. 

> 
> Regarding the blog article, are we talking about /blog/posts/intro-to-bjds/? If so i can make these changes.

Yes. Although It's not too big of deal to be honest. It's not a blocker.

**Comment by mxrmrtz** [comment]
Would you like us to open a new PR, or keep it all the new updates in this one?

**Comment by mxrmrtz** [comment]
> Here is the consolidated list I recommend we address to complete the rebrand:
> 
> * A style guide detailing the different formats and and icons, with mock up examples.
> * A logo pack with Folder structure. This will also have all the different formats and sizes. (You can [download my ZIP file](https://www.o3de.org/files/O3DE-Logo-Pack.zip) for a folder reference of files expected for a industry standard logo pack – Also make sure to include Regular, Reverse, Mono, Mono Reverse and, PNG, SVG, JPG and EPS)
> * Branding collaterals or mock up examples. [This PR](https://github.com/o3de/o3de/pull/9282) has some good screenshots that can provide context for UI examples.
> * Assets Update to the [O3DE Website](https://o3de.org/). Logo’s need to be replaced in any reference on all pages. (This is that PR)
> * Updates to the [Branding website](https://www.o3de.org/docs/tools-ui/branding-guidelines/) for O3DE logo. (This is that PR)
> * Update to the O3DE Docs Footer logo. (This is that PR)
> * A press kit that people can download for announcements for the new O3DE release.

Would you like us to open a new PR, or keep posting the updates in this PR

**Comment by yuyihsu** [comment]
> > Here is the consolidated list I recommend we address to complete the rebrand:
> > 
> > * A style guide detailing the different formats and and icons, with mock up examples.
> > * A logo pack with Folder structure. This will also have all the different formats and sizes. (You can [download my ZIP file](https://www.o3de.org/files/O3DE-Logo-Pack.zip) for a folder reference of files expected for a industry standard logo pack – Also make sure to include Regular, Reverse, Mono, Mono Reverse and, PNG, SVG, JPG and EPS)
> > * Branding collaterals or mock up examples. [This PR](https://github.com/o3de/o3de/pull/9282) has some good screenshots that can provide context for UI examples.
> > * Assets Update to the [O3DE Website](https://o3de.org/). Logo’s need to be replaced in any reference on all pages. (This is that PR)
> > * Updates to the [Branding website](https://www.o3de.org/docs/tools-ui/branding-guidelines/) for O3DE logo. (This is that PR)
> > * Update to the O3DE Docs Footer logo. (This is that PR)
> > * A press kit that people can download for announcements for the new O3DE release.
> 
> Would you like us to open a new PR, or keep posting the updates in this PR

@mxrmrtz can you start a new PR to address all the branding issues we've discovered so far? We won't be blocking the release due to these issues, but it should be a fast follow up after the new release. The inconsistent branding is visible across the social media, website and in product, which isn't good for O3DE branding in general.

**Pull request merged**
