### PR TITLE
Cherry pick main back to development

### PR DESCRIPTION
**Pull request by jhanca-robotecai**
## Change summary

This PR cherry-picks changes that were pushed to the `main` branch (directly or via _stabilization_ branches) and that were not pushed to the `development` branch causing the misalignment. 

In December I synchronized the branches by doing the following cherry-picks:
aaa7c603075cd9510c23c5b9a12974f834a5fa1b
f5dad19f028e69401d2dc9d768010b204433dda9
133b8f26deb707d841b295652db8fe17a51f1f98
d9d3a036c0e2d7b4a49a9f143f4c9fcfe98f7e0e
b816fd7a197c8a55f62fd4f3cf65621bc8fe2047
05fa6a392aa26a0aa98a2e8b8f954fde3c907d9d
da33e38f5a4c71733504122c46dca52548d4bd1a
b7fe90c4a45773d66e902c276c1e55b64d45cdc7
14dea04f3e7c297a754893872b9b9e80d7bbb759

Unfortunately, the code was not reviewed and not merged. Today (July 4) I picked up the task again and created a supportive branch on which I created the linear history for cherry-picking for all commits that entered `main` branch after the synchronization that took place earlier. The branch is pushed to this repo for the reviewer's convenience: `jhanca-robotecai/main_linear23101` . Note, that there is no difference between the `HEAD` of `jhanca-robotecai/main_linear23101` and the `HEAD` of `main`. Thanks to the linear history, I was able to cherry-pick the code on top of this branch. I.e. I was able to cherry-pick all commits from the main branch between b7fe90c4a4 and 31622c5294

## Testing

I pushed one more branch for the reviewer's convenience: `jhanca-robotecai/main_development`. I cherry-picked to this branch all commits that entered the `development` branch after the last `main` updates. When comparing `jhanca-robotecai/main_development` with `jhanca-robotecai/merge_main` there are several differences, caused by the fact that was merged into `development` and never made into `main`:
- 995992f https://github.com/o3de/o3de.org/pull/2447
- f8a54bc https://github.com/o3de/o3de.org/pull/2493
- dab5cd9 https://github.com/o3de/o3de.org/pull/2507
- 39c1163: https://github.com/o3de/o3de.org/pull/2517
- 220e0fc https://github.com/o3de/o3de.org/pull/2533

This proves I did not miss any changes in `main` branch.

## Concerns

I am aware it is impossible to review this PR due to the size of the change. This is caused by the cherry-pick of https://github.com/o3de/o3de.org/pull/2475 which is equally big. I did not change those files myself, but AFAIK those are autogenerated files that should be updated again. I might revert those changes to make this PR easier to review. Just let me know. Otherwise, feel free to push the code to my branch or open PR to my branch. Thanks for help!

### CODE REVIEW

**Comment by jhanca-robotecai** [comment]
I might add my signature to the cherry-picked commits if this is required by the procedure (DCO), but I thought it would be okay to keep it as is. Please let me know.

**Comment by ShaunaGordon** [comment]
Note, for reference purposes

Jan is picking this back up and updating it to include merges since this PR was submitted. I'll then be reviewing and testing it so we can get it merged asap.

**Comment by jhanca-robotecai** [comment]
I push-forced the code with the updates, please see the updated description in the first post.

**Comment by ShaunaGordon** [comment]
👍🏼 

@RoddieKieley Looks good to me. Just need you to hit the approve button and do the merge.

**Comment by adamdbrw** [comment]
@RoddieKieley could you take a look at this?

**Comment by jhanca-robotecai** [comment]
There was another conflict due to the recent changes to documentation in 
https://github.com/o3de/o3de.org/pull/2578

Unfortunately, this PR missed the changes from https://github.com/o3de/o3de.org/pull/2519 and https://github.com/o3de/o3de.org/pull/2514 that were pushed directly to the stabilization branch.

I decided to keep only changes from #2578.

**Comment by jhanca-robotecai** [comment]
Force-pushed the PR again to fix DCO: all commits are signed by myself.

**Comment by jhanca-robotecai** [comment]
> @RoddieKieley Looks good to me. Just need you to hit the approve button and do the merge.

@ShaunaGordon could you please give an _approve_ this PR?

**Review by ShaunaGordon — APPROVED** [review]

**Pull request merged**
