### PR TITLE
Hide AI component docs

### LINKED ISSUE #187: [Incorrect links] Hyperlink leads the User to main chapter instead of target location
Link to the Page: https://o3deorg.netlify.app/docs/user-guide/components/reference/nav-area/
in chapter: Navigation Area
https://o3deorg.netlify.app/docs/user-guide/components/reference/nav-area/#render-navigation-mesh link assigned to " render the navigation mesh" hyperlink redirects the User to the same chapter where the hyperlink is included instead of target chapters.

Link to the Page: https://o3deorg.netlify.app/docs/user-guide/components/reference/physx-shape-collider/
in chapter: PhysX Shape Collider
https://o3deorg.netlify.app/docs/user-guide/components/reference/physx-shape-collider/#physx-shape-collider
https://o3deorg.netlify.app/docs/user-guide/components/reference/physx-shape-collider/#physx-shape-collider-properties
https://o3deorg.netlify.app/docs/user-guide/components/reference/physx-shape-collider/#complex-polygon-prism-shapes
https://o3deorg.netlify.app/docs/user-guide/components/reference/physx-shape-collider/#colliders-as-triggers
link assigned to
"PhysX Shape Collider {#component-physx-shape-collider}"
"PhysX Shape Collider properties {#component-physx-shape-collider-properties}"
"Complex polygon prism shapes {#complex-polygon-prism-shapes}"
"Colliders as triggers {#colliders-as-triggers}"
hyperlink redirects the User to the same chapter where the hyperlink is included instead of target chapters.

Link to the Page: https://o3deorg.netlify.app/docs/user-guide/components/reference/random-timed-spawner/
in chapter: Random Timed Spawner
https://o3deorg.netlify.app/docs/user-guide/components/reference/random-timed-spawner/#random-timed-spawner-component-random-timed-spawner
https://o3deorg.netlify.app/docs/user-guide/components/reference/random-timed-spawner/#random-timed-spawner-properties-component-random-timed-spawner-properties
https://o3deorg.netlify.app/docs/user-guide/components/reference/random-timed-spawner/#timing-component-random-timed-spawner-timing
https://o3deorg.netlify.app/docs/user-guide/components/reference/random-timed-spawner/#ebus-request-bus-interface-component-random-timed-spawner-ebus-request
https://o3deorg.netlify.app/docs/user-guide/components/reference/random-timed-spawner/#enable-random-timed-spawner-ebus-enabled
https://o3deorg.netlify.app/docs/user-guide/components/reference/random-timed-spawner/#disable-random-timed-spawner-ebus-disable
https://o3deorg.netlify.app/docs/user-guide/components/reference/random-timed-spawner/#toggle-random-spawner-component-ebus-toggle
https://o3deorg.netlify.app/docs/user-guide/components/reference/random-timed-spawner/#isenabled-random-timed-spawner-ebus-is-enabled
https://o3deorg.netlify.app/docs/user-guide/components/reference/random-timed-spawner/#setrandomdistribution-random-timed-spawner-ebus-set-random-distribution
https://o3deorg.netlify.app/docs/user-guide/components/reference/random-timed-spawner/#getrandomdistribution-random-timed-spawner-ebus-get-random-distribution
https://o3deorg.netlify.app/docs/user-guide/components/reference/random-timed-spawner/#setspawndelay-random-timed-spawner-ebus-set-spawn-delay
https://o3deorg.netlify.app/docs/user-guide/components/reference/random-timed-spawner/#getspawndelay-random-timed-spawner-ebus-get-spawn-delay
https://o3deorg.netlify.app/docs/user-guide/components/reference/random-timed-spawner/#setspawndelayvariation-random-timed-spawner-ebus-set-spawn-delay-variation
https://o3deorg.netlify.app/docs/user-guide/components/reference/random-timed-spawner/#getspawndelayvariation-random-timed-spawner-ebus-get-spawn-delay-variation
https://o3deorg.netlify.app/docs/user-guide/components/reference/random-timed-spawner/#notification-bus-example-script-random-timed-spawner-notification-bus-example-script
link assigned to
"Random Timed Spawner {#component-random-timed-spawner}"
"Random Timed Spawner Properties {#component-random-timed-spawner-properties}"
"Timing {#component-random-timed-spawner-timing}"
"EBus Request Bus Interface {#component-random-timed-spawner-ebus-request}"
"Enable {#random-timed-spawner-ebus-enabled}"
"Disable {#random-timed-spawner-ebus-disable}"
"Toggle {#random-spawner-component-ebus-toggle}"
"IsEnabled {#random-timed-spawner-ebus-is-enabled}"
"SetRandomDistribution {#random-timed-spawner-ebus-set-random-distribution}"
"GetRandomDistribution {#random-timed-spawner-ebus-get-random-distribution}"
"SetSpawnDelay {#random-timed-spawner-ebus-set-spawn-delay}"
"GetSpawnDelay {#random-timed-spawner-ebus-get-spawn-delay}"
"SetSpawnDelayVariation {#random-timed-spawner-ebus-set-spawn-delay-variation}"
"GetSpawnDelayVariation {#random-timed-spawner-ebus-get-spawn-delay-variation}"
"Notification Bus Example Script {#random-timed-spawner-notification-bus-example-script}"
hyperlink redirects the User to the same chapter where the hyperlink is included instead of target chapters.

### PR DESCRIPTION
**Pull request by FiniteStateGit**
Hide reference/ai directory.
Hide reference to ai components in O3de core (lmbrcentral) gem.
Hide reference in component reference index.

Fix #187

### CODE REVIEW

**Review by micronAMZN — APPROVED** [review]

**Review by willihay — CHANGES_REQUESTED** [review]
I'm not sure that hiding these docs is the right fix. These Navigation components still appear in a recent build of O3DE, so they're still available - and working, hopefully.

The issue linked in the description of this PR is referring to some bad links in nav-area.md (line 17, for example). Basically, the fix for this is to look for all the internal links like these and either correct the link name (which you can verify by looking at the same doc on Lumberyard) or in some cases, make the link destination into an H3 header (line 23, for example).

Feel free to assign the original issue to me if you want.

**Comment by FiniteStateGit** [comment]
> I'm not sure that hiding these docs is the right fix. These Navigation components still appear in a recent build of O3DE, so they're still available - and hopefully working.

I am completely ignorant of any plans regarding these components, but afaik they are non-functional, and the related tools to edit/generate nav meshes in the editor are absent with the gems enabled.  I thought that they might be legacy components included with LmbrCentral pending some edit to the gem itself.  So the linked issue would be closed due the page being deprecated.

I'm open to resolving this and the other PRs any way.  I pushed them as a way to start the conversation on content that might stay out-of-date for the time being.

**Comment by sptramer** [comment]
I don't think it's a bad idea to unpublish docs that don't represent the current state of the product, even if there's background ongoing development to re-enable or rename the features. We should probably hide these, then open a corresponding issue to re-populate them with correct info.

**Review by willihay — APPROVED** [review]
I researched the status of the AI Navigation components and found that they have recently been hidden from use in recent builds while the community determines whether to fix or remove them. (Reference: O3DE PR # 3447.)

**Pull request merged**
