### PR TITLE
Billboard Tutorial

### PR DESCRIPTION
**Pull request by judysng**
## Change summary

Added a draft for the tutorial for the [billboard component](https://github.com/o3de/sample-code-gems/pull/11). There will probably be more changes to the code & to the tutorial, but making a PR for visibility for now before I leave today. 

### Submission Checklist:

* [ ] **Descriptive active voice** - Do descriptive sentences have a clear *subject* and *action verb*?
* [ ] **Answer the question at hand** - Does the documentation answer a *what*, *why*, *how*, or *where* type of question?
* [ ] **Consistency** - Does the content consistently follow the [style guide](https://o3de.org/docs/contributing/to-docs/style-guide/)?
* [ ] **Help the user** - Does the documentation show the user something *meaningful*?

### CODE REVIEW

**Comment by chanmosq** [comment]
This document is still work in progress. Pending work with @galibzon.

**Comment by ShaunaGordon** [comment]
@chanmosq @galibzon @judysng Is this still being worked on, or has it been abandoned? 

If you're no longer working on it, what exactly is blocking it? Could it be made merge-ready if someone else picks it up?

If you're still working on it, do you have any progress updates for it? And can you please switch it to merge into development?

Thanks!

**Comment by chanmosq** [comment]
Hello @ShaunaGordon, I don't believe this will have any more updates from the original authors as they've all left now. If I recall, it was marked with do-not-merged because of planned review, which is overdue and likely will not happen anymore. I'd advise to either publish it or archive it for someone else to pick up.

**Comment by ShaunaGordon** [comment]
@chanmosq Thanks for the information.

@RoddieKieley Let's go ahead and close this without merging, given the age (since a video is included). If someone wants to create a new tutorial, we can point them to this one for some reference.

**Pull request closed without merging**
