### PR TITLE
Update latest version date to October 9.md

### PR DESCRIPTION
**Pull request by Naomi-Wash**
### Submission Checklist:

* [ ] **Descriptive active voice** - Do descriptive sentences have a clear *subject* and *action verb*?
* [ ] **Answer the question at hand** - Does the documentation answer a *what*, *why*, *how*, or *where* type of question?
* [ ] **Consistency** - Does the content consistently follow the [Style Guide](https://o3de.org/docs/contributing/to-docs/style-guide/quick-reference)?
* [ ] **Help the user** - Does the documentation show the user something *meaningful*?

### CODE REVIEW

**Review by ShaunaGordon — APPROVED** [review]

**Review by ShaunaGordon — CHANGES_REQUESTED** [review]
Needs merged into dev, then put into main, not directly into main.

**Comment by Naomi-Wash** [comment]
Changed the branch to development.

**Comment by ShaunaGordon** [comment]
@Naomi-Wash yikes, it looks like the branch you branched from is out of sync with the development branch. Can you either rebase or redo your feature branch so that it's in sync with the development branch and only your changes are listed in the PR? Thanks!

**Comment by jhanca-robotecai** [comment]
This commit was cherry-picked to the `development` branch as a part of the bigger PR that was squashed (the `development` branch protection rules are set to _squash and rebase_). I would suggest to target it back to the `main` branch as a part of the _point release_.

**Comment by jhanca-robotecai** [comment]
@ShaunaGordon, I created a point release branch and retargeted this PR. Please re-review it and approve it if you agree.

**Review by jhanca-robotecai — APPROVED** [review]

**Comment by ShaunaGordon** [comment]
Looks good to me. 👍🏼

**Review by ShaunaGordon — APPROVED** [review]

**Pull request merged**
