### PR TITLE
Add Remote Tools Gem doc and related updates

### PR DESCRIPTION
**Pull request by AMZN-puvvadar**
Signed-off-by: puvvadar <puvvadar@amazon.com>

## Change summary

This change adds documentation for work proposed in https://github.com/o3de/o3de/pull/9785

### Submission Checklist:

* [x] **Descriptive active voice** - Do descriptive sentences have a clear *subject* and *action verb*?
* [x] **Answer the question at hand** - Does the documentation answer a *what*, *why*, *how*, or *where* type of question?
* [x] **Consistency** - Does the content consistently follow the [style guide](https://o3de.org/docs/contributing/to-docs/style-guide/)?
* [x] **Help the user** - Does the documentation show the user something *meaningful*?

### CODE REVIEW

**Comment by FiniteStateGit** [comment]
@AMZN-puvvadar Is this ready for editors to review?

**Comment by AMZN-puvvadar** [comment]
> @AMZN-puvvadar Is this ready for editors to review?

Yes please. The code change is outstanding but the docs should be ready to review.

**Review by FiniteStateGit — CHANGES_REQUESTED** [review]

**Review by FiniteStateGit — APPROVED** [review]

**Review by willihay — APPROVED** [review]

**Comment by willihay** [comment]
@AMZN-puvvadar I don't see the Gem in the source development branch yet. Would you like to put a hold on this PR until that's checked in?

**Comment by AMZN-puvvadar** [comment]
@willihay The change in the o3de repo has been submitted and this is now ready to merge.

**Pull request merged**
