### PR TITLE
Update Niantic partner logo to latest.

### PR DESCRIPTION
**Pull request by sptramer**
Review for visual confirmation that this is the correct logo and merge when signed off.

### CODE REVIEW

**Review by OBWANDO — APPROVED** [review]
Logo change from Black to red. LGTM

**Comment by OBWANDO** [comment]
Looks good (testing webhook)

**Comment by amzn-leenguy** [comment]
Hello @OBWANDO . Any chance you could get us the SVG version of this logo? We are trying to avoid PNGs. As it doesn't align with good web practices. Thanks! Once you get the asset, please let me know. @AMZN-daimini and I can fix it.

**Comment by amzn-leenguy** [comment]
@OBWANDO all good now. we got the svg. please ignore my top request.

**Pull request merged**
